server:
    port: 8250
kubernetes:
    master: 121.36.70.254:8080
rocketmq:
    consumer:
        isOnOff: on
        groupName: device-data-consumer
        namesrvAddr: 123.56.46.27:9876
        topics: device-data,*
        consumeThreadMin: 5
        consumeThreadMax: 32
        consumeMessageBatchMaxSize: 1

