server:
    port: 8250
kubernetes:
    master: 121.36.70.254:8080
rocketmq:
    consumer:
        isOnOff: on
        groupName: device-data-consumer
        namesrvAddr: 123.56.46.27:9876
        topics: device-data,*
        consumeThreadMin: 5
        consumeThreadMax: 32
        consumeMessageBatchMaxSize: 1

spring:
    redis:
        database: 0
        host: 123.56.46.27
        port: 6379
        pool:
            max-active: 4
            max-wait: -1
            max-idel: 4
            min-idel: 0
        timeout: 1000

